version: '3'
services:
  db:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=adit_root_db
      - MYSQL_DATABASE=adit
      - MYSQL_USER=adit
      - MYSQL_PASSWORD=adit_server_1
      - LANG=ru_RU.UTF-8
    ports:
      - 3306:3306
    volumes:
      - ./src/main/resources/migration/init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=adit_root_db --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  app:
    image: adit
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy