spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adit
    username: adit
    password: adit_server_1
  application:
    name: adit
  data:
    redis:
      host: localhost
      port: 6379
      password: redispassword
  rabbitmq:
    port: 5672
    host: localhost
    username: notification_service
    password: notification_service
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  token:
    secret: adit
image:
  path: images
server:
  port: 8080

