-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 17:26:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `adit` ;

-- -----------------------------------------------------
-- Schema adit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adit` DEFAULT CHARACTER SET utf8 ;
USE `adit` ;

-- -----------------------------------------------------
-- Table `adit`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`user` ;

CREATE TABLE IF NOT EXISTS `adit`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `age` DATE NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`role` ;

CREATE TABLE IF NOT EXISTS `adit`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`user_role` ;

CREATE TABLE IF NOT EXISTS `adit`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `role_id_from_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `user_to_user_role_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `adit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_to_user_role_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `adit`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`address` ;

CREATE TABLE IF NOT EXISTS `adit`.`address` (
  `address_id` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `part` VARCHAR(45) NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`advertisement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`advertisement` ;

CREATE TABLE IF NOT EXISTS `adit`.`advertisement` (
  `ad_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `status` int NOT NULL,
  `price` decimal null,
  `placed_at` TIMESTAMP NOT NULL,
  `address_id` INT NULL,
  `user_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`ad_id`),
  INDEX `user_to_ad_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `address_to_ad_fk_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `user_to_ad_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `adit`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `address_to_ad_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `adit`.`address` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
CONSTRAINT `category_to_ad_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `adit`.`category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`category` ;

CREATE TABLE IF NOT EXISTS `adit`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `parent_id_fk_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `parent_id_fk`
    FOREIGN KEY (`parent_id`)
    REFERENCES `adit`.`category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`feature` ;

CREATE TABLE IF NOT EXISTS `adit`.`feature` (
  `feature_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(1000) NULL,
  PRIMARY KEY (`feature_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`category_feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`category_feature` ;

CREATE TABLE IF NOT EXISTS `adit`.`category_feature` (
  `category_id` INT NOT NULL,
  `feature_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `feature_id`),
  INDEX `feature_id_to_cf_fk_idx` (`feature_id` ASC) VISIBLE,
  CONSTRAINT `category_id_to_cf_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `adit`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `feature_id_to_cf_fk`
    FOREIGN KEY (`feature_id`)
    REFERENCES `adit`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adit`.`advertisement_feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adit`.`advertisement_feature` ;

CREATE TABLE IF NOT EXISTS `adit`.`advertisement_feature` (
  `advertisement_id` INT NOT NULL,
  `feature_id` INT NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`advertisement_id`, `feature_id`),
  INDEX `feature_id_to_adv_feature_fk_idx` (`feature_id` ASC) VISIBLE,
  CONSTRAINT `adv_id_to_adv_feature_fk`
    FOREIGN KEY (`advertisement_id`)
    REFERENCES `adit`.`advertisement` (`ad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `feature_id_to_adv_feature_fk`
    FOREIGN KEY (`feature_id`)
    REFERENCES `adit`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `adit`.`image` ;

create table if not exists `adit`.`image`(
    image_id         int auto_increment
        primary key,
    filename         varchar(128) not null,
    advertisement_id int          not null,
    extension        varchar(16)  not null,
    constraint image___fk_adv_id
        foreign key (advertisement_id) references adit.advertisement (ad_id)
            on update cascade on delete cascade
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
